pipeline {
    agent {label "docker-agent"}

    stages {
        stage('Pull NGINX Image') {
            steps {
                script {
                    sh 'docker pull nginx:latest'
                }
            }
        }
        stage("Run container") {
            steps {
                script {
                    sh 'docker run -d --name dind-nginx -p 8000:80 nginx:latest'
                }
            }
        }
    }
}