pipeline {
    agent {label "docker-agent"}

    environment{
        DOCKERHUB_CRED = credentials("Dockerhub_CRED")
    }
    stages {
        stage('docker ps') {
            steps {
                sh 'docker ps'
            }
        }
        stage("Docker ligin") {
            steps {
                    sh ' echo "${DOCKERHUB_CRED_PSW}" | docker login --username "${DOCKERHUB_CRED_USR}" --password-stdin'
                
            }
        }
    }
}

/*
stages {
        stage('Pull NGINX Image') {
            steps {
                script {
                    sh 'docker pull nginx:latest'
                }
            }
        }
        stage("Run container") {
            steps {
                script {
                    sh 'docker run -d --name dind-nginx -p 8000:80 nginx:latest'
                }
            }
        }
    }
*/